### ISSUE TITLE
AD0001 when using StringBuilder.AppendLine()

### ISSUE THREAD

**Issue by daze99** [dotnet/roslynator#1225]
**Product and Version Used**: 
Roslynator 4.6.0 in Visual Studio 17.7.5

**Steps to Reproduce**:
```csharp
public static string Test()
{
    var strBuilder = new StringBuilder();
    _ = strBuilder.AppendLine();

    return strBuilder.ToString();
}

```

**Actual Behavior**:
There is a warning AD0001
```
System.InvalidOperationException: Object is not initialized.
   at Roslynator.CSharp.Syntax.SimpleMemberInvocationExpressionInfo.get_Name()
   at Roslynator.CSharp.Syntax.SimpleMemberInvocationExpressionInfo.get_NameText()
   at Roslynator.CSharp.Analysis.OptimizeStringBuilderAppendCallAnalysis.Analyze(SyntaxNodeAnalysisContext context, SimpleMemberInvocationExpressionInfo& invocationInfo)
   at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__49`1.<ExecuteSyntaxNodeAction>b__49_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
```
**Expected Behavior**:
No warning should occur.

**Comment by bdovaz** [comment]
@josefpihrt are you going to release a patch soon? Thanks!

**Comment by josefpihrt** [comment]
@bdovaz Patch will be released soon.

**Comment by josefpihrt** [comment]
https://github.com/dotnet/roslynator/releases/tag/v4.6.1
