### ISSUE TITLE
roslynator tool fails on removing unused code when project has code generated files

### ISSUE THREAD

**Issue by prezaei** [dotnet/roslynator#1549]
**Product and Version Used**: 
`roslynator find-symbol --symbol-kind type --unused --remove`
Latest version of the tool (4.1.7)

**Steps to Reproduce**:
We use .NET Source Generator for IOptions validation. These are not physical files and should be ignored by Roslynator. 

https://learn.microsoft.com/en-us/dotnet/core/extensions/options-validation-generator

**Actual Behavior**:
```bash
    class  __OptionValidationStaticInstances.__Validators
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslynator.CommandLine.FindSymbolCommand.RemoveSymbolsAsync(ImmutableArray`1 symbols, Project project, CancellationToken cancellationToken) in /_/src/CommandLine/Commands/FindSymbolCommand.cs:line 181
   at Roslynator.CommandLine.FindSymbolCommand.ExecuteAsync(ProjectOrSolution projectOrSolution, CancellationToken cancellationToken) in /_/src/CommandLine/Commands/FindSymbolCommand.cs:line 99
   at Roslynator.CommandLine.MSBuildWorkspaceCommand`1.ExecuteAsync(String path, MSBuildWorkspace workspace, CancellationToken cancellationToken) in /_/src/CommandLine/Commands/MSBuildWorkspaceCommand.cs:line 164
   at Roslynator.CommandLine.MSBuildWorkspaceCommand`1.ExecuteAsync(IEnumerable`1 paths, String msbuildPath, IEnumerable`1 properties) in /_/src/CommandLine/Commands/MSBuildWorkspaceCommand.cs:line 89
   at Roslynator.CommandLine.Program.FindSymbolAsync(FindSymbolCommandLineOptions options) in /_/src/CommandLine/Program.cs:line 392
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Roslynator.CommandLine.Program.<>c.<Main>b__0_3(MSBuildCommandLineOptions options) in /_/src/CommandLine/Program.cs:line 195
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at Roslynator.CommandLine.Program.Main(String[] args) in /_/src/CommandLine/Program.cs:line 169
```

**Comment by josefpihrt** [comment]
I agree that it's a bug, but can you just run it with `--ignore-generated-code` to see if it helps? Thanks.

**Comment by prezaei** [comment]
For sure. That is what I had done. Was just reporting it.

Also, it seems to delete test cases. Would be good to exclude those too.

**Comment by josefpihrt** [comment]
Regarding the options validation, could you provide a code sample?

Is this the class that is being reported as unused (this is just an example copied from docs):
```
using Microsoft.Extensions.Options;

namespace ConsoleJson.Example;

[OptionsValidator]
public partial class ValidateSettingsOptions : IValidateOptions<SettingsOptions>
{
}
```

Regarding the tests, which test framework are you talking about? Please provide code sample.
